- name: Create template from OVF
  hosts: all
  gather_facts: false
  collections:
    - community.vmware
  tasks:
    - name: Get OVF file from URL
      get_url:
        url: "http://192.168.8.248/rhcos-4.3.8-x86_64-vmware.x86_64.ova"
        dest: "/tmp/rhcos-4.3.8-x86_64-vmware.x86_64.ova"
      delegate_to: localhost
    - name: Copy file to datastore from controller
      vsphere_copy:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        src: "/tmp/rhcos-4.3.8-x86_64-vmware.x86_64.ova"
        #src: "{{ lookup('env', 'VMWARE_SOURCE_HTTP_SERVER')+'/'+lookup('env', 'VMWARE_TEMPLATE') }}"
        datacenter: osdatacenter1
        datastore: osvsandatastore1
        path: "templates/rhcos-4.3.8-x86_64-vmware.x86_64.ova"
        #path: "{{ 'templates/'+lookup('env', 'VMWARE_TEMPLATE') }}"
      delegate_to: localhost
    - name: Deploy OVF
      vmware_deploy_ovf:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        datacenter: osdatacenter1
        cluster: vmwocp4
        datastore: osvsandatastore1
        name: NewVM
        validate_certs: no
        power_on: no
        ovf: "templates/rhcos-4.3.8-x86_64-vmware.x86_64.ova"
        #ovf: "{{ 'templates/'+lookup('env', 'VMWARE_TEMPLATE') }}"
      delegate_to: localhost
