- name: Create template from OVF
  hosts: all
  gather_facts: false
  collections:
    - community.vmware
  tasks:
    - name: Copy file to datastore from URL
      vsphere_copy:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        src: "{{ lookup('env', 'VMWARE_SOURCE_HTTP_SERVER')+'/'+lookup('env', 'VMWARE_TEMPLATE') }}"
        datacenter: osdatacenter1
        datastore: osvsandatastore1
        path: "{{ 'templates/'+lookup('env', 'VMWARE_TEMPLATE') }}"
      delegate_to: localhost
    - name: Deploy OVF
      vmware_deploy_ovf:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        datacenter: osdatacenter1
        cluster: vmwocp4
        datastore: osvsandatastore1
        name: NewVM
        validate_certs: no
        power_on: no
        ovf: "{{ 'templates/'+lookup('env', 'VMWARE_TEMPLATE') }}"
      delegate_to: localhost
