- name: Create VM from template
  hosts: all
  gather_facts: false
  collections:
    - community.vmware
  tasks:
    - name: Create VM
      vmware_guest:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        datacenter: osdatacenter1
        cluster: vmwocp4
        resource_pool: vmwocp4
        name: NewVM
        validate_certs: no
        folder: /vmwocp4
        state: present
        template: rhcos-4.3.8-x86_64-vmware.x86_64
        is_template: no
        disk:
          - size_gb: 60
            type: thin
            datastore: osvsandatastore1
        hardware:
          memory_mb: 32768
          num_cpus: 8
        networks:
          - name: DSwitch-VM Network
          start_connected: True
        customvalues:
          - key: "disk.EnableUUID"
            value: "TRUE"
        wait_for_ip_address: no
      delegate_to: localhost
