- name: Deploy OVF
  hosts: all
  gather_facts: false
  collections:
    - community.vmware
  tasks:
    - name: Create VM
      vmware_deploy_ovf:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        datacenter: osdatacenter1
        cluster: vmwocp4
        datastore: osvsandatastore1
        name: NewVM
        networks: "{u'VM Network':u'DSwitch-VM Network'}"
        validate_certs: no
        power_on: no
        ovf: /rhcos-4.3.8-x86_64-vmware.x86_64.ova
      delegate_to: localhost
