- name: Gather info from vCenter
  hosts: all
  gather_facts: false
  collections:
    - community.vmware
  tasks:
    - name: Gather all registered virtual machines
      vmware_vm_info:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
      delegate_to: localhost
      register: vminfo
