- name: Gather info from vCenter
  hosts: all
  collections:
    - community.vmware
  tasks:
    - name: Gather all registered virtual machines
      vmware_vm_info:
        hostname: '192.168.8.206'
        username: 'osadmin@osvsphere.local'
        password: 'Init123!'
      delegate_to: localhost
      register: vminfo
